[package]
authors = ["Weslei Juan Moser Pereira <wesleimsr@gmail.com>"]
edition = "2018"
name = "file-prune"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quicli = "0.2"
walkdir = "2"
